import "~/styles/globals.css";
import localFont from "next/font/local";
import type { Metadata } from "next";


export const metadata: Metadata = {
	title: "McCarty Landing",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// Define Barlow font
const barlowFont = localFont({
	src: [
	  {
		path: "../fonts/barlow-latin-400-normal-7fa387951673abf164b13dd1b45c70e3.woff2",
		weight: "400",
		style: "normal",
	  },
	  {
		path: "../fonts/barlow-latin-500-normal-50adbbfa3bfe480bf4246ff5bad7ad06.woff2",
		weight: "500",
		style: "normal",
	  },
	  {
		path: "../fonts/barlow-latin-700-normal-dd5b2912dbf896310865c1e9ac85ab41.woff2",
		weight: "700",
		style: "normal",
	  },
	],
	variable: "--font-barlow",
	display: "swap",
  })
  
  // Define Colfax font
  const colfaxFont = localFont({
	src: [
	  {
		path: "../fonts/ColfaxWebRegular-ffe8279204a8eb350c1a8320336a8e1a.woff2",
		weight: "400",
		style: "normal",
	  },
	  {
		path: "../fonts/ColfaxWebMedium-5cd963f45f4bd8647a4e41a58ca9c4d3.woff2",
		weight: "500",
		style: "normal",
	  },
	],
	variable: "--font-colfax",
	display: "swap",
  })
  
  
  const featureFont = localFont({
	src: [
	  {
		path: "../fonts/FeatureFlatHeadline.c189951b.woff2",
		weight: "400",
		style: "normal"
	  },
	  {
		path: "../fonts/FeatureFlatText-Bold.4f87c9cd.otf",
		weight: "700",
		style: "normal"
	  }
	],
	variable: "--font-feature",
	display: "swap",
  })
  
  const featureCondensedFont = localFont({
	src: [
	  {
		path: "../fonts/FeatureFlatCond-Regular.a6231343.woff2",
		weight: "400", // Corresponds to Regular
		style: "normal",
	  },
	  {
		path: "../fonts/FeatureFlatCond-Medium.595cb47e.woff2",
		weight: "500", // Corresponds to Medium
		style: "normal",
	  },
	  // Add other CONDENSED weights/styles if you have them
	],
	variable: "--font-feature-condensed", // Distinct variable name
	display: "swap",
  })

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${barlowFont.variable} ${colfaxFont.variable} ${featureFont.variable} ${featureCondensedFont.variable}`}>
			<body className="font-sans">{children}</body>
		</html>
	);
}
